routes/admin.php
<?php

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function() {

	/*
	* Dashboard
	**/
	Route::get('/', 'DashboardController@index')->name('dashboard');

	/*
	* Deals
	**/
	Route::group(['prefix' => 'deals'], function() {
		Route::get('/', 'DealsController@index')->name('deals');
		Route::get('{list}/details', 'DealsController@details')->name('deals.details');
	});

	/*
	* Agents
	**/
	Route::group(['prefix' => 'agents'], function() {
		Route::get('/', 'AgentsController@index')->name('agents');
		Route::get('review', 'AgentsController@reviewAgents')->name('agents.review');
		Route::get('view', 'AgentsController@viewAgents')->name('agents.view');
		Route::get('deals', 'AgentsController@deals')->name('agents.deals');
		Route::post('search-results', 'AgentsController@searchResults')->name('agents.search-results');
		Route::get('{agent}/profile/{status?}', 'AgentsController@profile')->name('agents.profile');
		Route::post('{agent}/profile/store', 'AgentsController@storeProfile')->name('agents.profile.store');
		Route::post('{agent}/profile/store-qa', 'AgentsController@storeQA')->name('agents.profile.storeQA');
		Route::post('{agent}/profile/store-social', 'AgentsController@storeSocial')->name('agents.profile.storeSocial');
		Route::get('{agent}/profile/list/{list}/details', 'AgentsController@listDetails')->name('agents.profle.list-details');
		
		// ajax functions 
		Route::post('{agent}/approve', 'AgentsController@approve');
		Route::post('{agent}/reject', 'AgentsController@reject');
	});

	/*
	* Customer
	**/
	Route::group(['prefix' => 'customers'], function() {
		Route::get('/', 'CustomersController@index')->name('customers');
		Route::get('screen', 'CustomersController@customersToScreen')->name('customers.to-screen');
		Route::get('all', 'CustomersController@allCustomers')->name('customers.all');
		Route::get('without-agent', 'CustomersController@customersWithoutAgent')->name('customers.without-agent');
		Route::post('search-results', 'CustomersController@searchResults')->name('customers.search-results');
		Route::get('{customer}/profile/{status?}', 'CustomersController@profile')->name('customers.profile');
		Route::post('{customer}/profile/store', 'CustomersController@storeProfile')->name('customers.save-profile');
		Route::get('{customer}/profile/list/{list}/details', 'CustomersController@listDetails')->name('customers.profile.list-details');

		// Ajax
        Route::get('list/create-list', 'CustomersController@creatingList');
        Route::post('list/update-list', 'CustomersController@updateList');
        Route::get('list/{list}/edit-list', 'CustomersController@getList');
		Route::post('list/{list}/edit-agents', 'CustomersController@editAgents');
		Route::post('list/{list}/store-agents', 'CustomersController@storeAgents');
		Route::post('list/{list}/store-list-agents', 'CustomersController@storeListAgents');
		Route::post('{customer}/approve', 'CustomersController@approve');
		Route::post('{customer}/reject', 'CustomersController@reject');

	});

	/*
	* Process
	**/
	Route::group(['prefix' => 'process'], function() {
		Route::get('/', 'ProcessController@index')->name('process');
		Route::get('deals', 'ProcessController@deals')->name('process.deals');
	});

	/*
	* Settings
	**/
	Route::group(['prefix' => 'settings'], function(){
		Route::get('/', 'SettingsController@index')->name('settings');
		Route::get('create', 'SettingsController@create')->name('settings.create');
		Route::post('store', 'SettingsController@store')->name('settings.store');
		Route::get('{user}/edit', 'SettingsController@edit')->name('settings.edit');
		Route::post('{user}/update', 'SettingsController@update')->name('settings.update');
		Route::get('{user}/destroy', 'SettingsController@destroy')->name('settings.destroy');
	});

});

routes/user.php
<?php

Route::group(['namespace' => 'User'], function(){

	/*
	* Agent Routes
	**/
	require base_path('routes/agent.php');

	/*
	* Customer Routes
	**/
	require base_path('routes/customer.php');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Model\Agent;

Route::get('testmail', function() {
	$agent = \App\Model\Agent::findOrFail(28);
	Mail::to('jessie.sytian@gmail.com')->send(new \App\Mail\AgentSignupMail($agent));
});

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

Route::get('/login', 'HomeController@userLogin')->name('login');

Route::get('admin/login', 'HomeController@adminLogin')->name('admin.login');
	
/*
* Facebook Login
**/
Route::group(['prefix' => 'facebook'], function() {
	Route::get('login', 'Auth\LoginController@redirectToProvider')->name('facebook.login');
	Route::get('authenticated', 'Auth\LoginController@fbAuth')->name('facebook.authenticated');
});

/*
*  Public View Routes
**/
Route::get('/', 'HomeController@home')->name('home');

/*
* Buyers
**/
Route::group(['prefix' => 'buyers'], function() {
	Route::get('/', 'BuyersController@index')->name('buyers');
	Route::get('find-an-agent', 'BuyersController@findAgent')->name('buyers.find-agent');
	Route::get('guide', 'BuyersController@guide')->name('buyers.guide');
	Route::get('process', 'BuyersController@process')->name('buyers.process');
});

/*
* Sellers
**/
Route::group(['prefix' => 'sellers'], function() {
	Route::get('/', 'SellersController@index')->name('sellers');
	Route::get('find-an-agent', 'SellersController@findAgent')->name('sellers.find-agent');
	Route::get('guide', 'SellersController@guide')->name('sellers.guide');
	Route::get('process', 'SellersController@process')->name('sellers.process');
});

/*
* Agent
**/
Route::group(['prefix' => 'agent'], function() {
	Route::get('/', 'AgentsController@index')->name('agent');
	Route::get('register', 'AgentsController@register')->name('agent.register');	
	Route::post('validate-form', 'AgentsController@validateForm');
	Route::post('submit-registration', 'AgentsController@submitRegistration')->name('agent.submit-registration');
	Route::get('register-success', 'AgentsController@success');

	// fb registration
	Route::get('{user}/fb-register', 'AgentsController@fbRegister')->name('agent.fb-register');
});

Route::get('about-us', 'HomeController@about')->name('about');
Route::get('terms-and-condition', 'HomeController@terms')->name('terms');
Route::get('privacy-policy', 'HomeController@privacy')->name('privacy');
Route::get('resources', 'HomeController@resources')->name('resources');
Route::get('contact-us', 'HomeController@contact')->name('contact');
Route::get('find-an-agent', 'HomeController@findAgent')->name('find-agent');

// request a call / contact us
Route::post('request-call', 'HomeController@requestCall')->name('request-call');
Route::post('contact-us', 'HomeController@contactUs')->name('request-contact');

/*
* Registration
**/
Route::group(['prefix' => 'register'], function() {
	Route::get('/', 'HomeController@register')->name('register');
    Route::post('/', 'HomeController@getForms')->name('get.forms');
	Route::post('validate-form', 'HomeController@validateForm');
	Route::post('store', 'HomeController@storeRegistration');
	Route::get('success/{user?}', 'HomeController@success')->name('register.success');

	// fb registration
	Route::get('{user}/fb-register', 'HomeController@fbRegister')->name('register.fb-register');
});

Route::group(['middleware' => 'auth'], function() {

	/*
	* Admin Routes
	**/
	require base_path('routes/admin.php');	

	/*
	* Regular User Routes
	**/
	require base_path('routes/user.php');
});

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Support\Facades\File;
use ImageResize;
use App\Model\Role;
use App\Model\Agent;
use App\Model\Customer;
use App\Model\Activity;
use Watson\Validating\ValidatingTrait;
use Illuminate\Support\Facades\Storage;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    use ValidatingTrait;

    protected $throwValidationExceptions = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'username',
        'email',
        'phone_num'
    ];

    protected $rules = [
        'first_name' => 'required',
        'last_name' => 'required',
        'email' => 'required|unique|email',
        'password' => 'required|min:8',
        //'phone_num' => 'required|numeric|min:11|nullable',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    /*
    * Relations
    **/
    public function role() 
    {
        return $this->belongsTo(Role::class);
    }

    public function asCustomer() 
    {
        return $this->hasOne(Customer::class);
    }

    public function asAgent() 
    {
        return $this->hasOne(Agent::class);
    }

    public function activities() 
    {
        return $this->hasMany(Activity::class);
    }

    /*
    *  Helper Methods
    **/
    public function isAdmin() 
    {

        if( $this->role ) 
        {
            if($this->role->slug != 'administrator') 
            {
                return false;
            }
        } else {
            return false;
        }

        return true;

    }

    public function isCustomer() 
    {
        if( !$this->asCustomer ) {
            return false;
        }
        return true;
    }    

    public function isAgent() 
    {   
        if( !$this->asAgent ) {
            return false;
        }
        return true;
    }   

    public function isRegularUser() 
    {

        if( $this->role ) {
            if( $this->role->slug != 'user' )
            {
                return false;
            }
        } else {
            return false;
        }

        return true;

    }

    public function isNewUser()
    {
        return $this->created_at->isSameDay(Carbon::today()) ?: false;
    }

    /*
    * Getter Methods
    **/
    public function getNameAttribute() 
    {
        return $this->first_name . " " . $this->last_name;
    }

    public function getphoneFormatAttribute() 
    {

        $phone = preg_replace(array('/\+/', '/\(/', '/\)/', '/\s/', '/\./', '/\-/', '/[a-zA-Z]/'), array(''), $this->phone_num);
        $phone = str_split($phone, 1);
        $phone = array_chunk($phone, 3);

        $phone[0] = '(' . implode('', $phone[0]) . ') ';

        if( isset( $phone[1] ) ) {
            $phone[1] = implode('', $phone[1]) . (count($phone) > 2 ? '-' : '');
        }

        if( count( $phone ) > 2 ) {
            for( $i = 2; $i < count($phone); $i++ ) {
                $phone[$i] = implode('', $phone[$i]);
            }
        }

        $phone = implode('', $phone);

        return $phone;

    }

    public function getProfilePhotoAttribute()
    {
        $publicPath = '';
        $profilePhoto = asset(Storage::disk('world')->url('profile-photos/' . $this->photo));
        $publicPath = public_path('storage/profile-photos/' . ($this->photo ?: 'false'));

        if( $this->photo && File::exists($publicPath))
        {
            $resizedPhoto = ImageResize::make($profilePhoto)->fit(278, 278)->encode('data-url');
        } else {
            $resizedPhoto = null;
        }

        return File::exists($publicPath) ? $resizedPhoto->encoded : null;
    }

}

resources/views/admin/index.blade.php
@extends('layouts.default')

<!-- Added Styles -->
@section('styles')
<style type="text/css">
    .prmenu-wrapper .nav-tabs {
        border: 0;
    }
</style>
@stop
@section('body-class')
    dashboard
@stop
@section('page-title')
    Dashboard
@stop

<!-- Content -->
@section('content')
<section class="main-dashboard">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">

                <div class="prmenu-wrapper">
                    <div class="prmenu-list equal-items nav nav-tabs row">
                        <div class="item active col-xs-12 col-sm-4">
                            <a href="#tab-customers" class="item-wrapper" data-toggle="tab">
                                <div class="bg" style="background-image:url({{asset('images/admin/dashboard/customer-leads.jpg')}})"></div>
                                <div class="content">
                                    <div class="icon" style="background-image:url({{asset('images/icon-agentsreview.svg')}})"></div>
                                    <h2 class="title">CUSTOMER LEADS</h2>
                                </div>
                            </a>
                        </div>

                        <div class="item col-xs-12 col-sm-4">                            
                            <a href="#tab-agents" class="item-wrapper" data-toggle="tab">
                                <div class="bg" style="background-image:url({{asset('images/admin/dashboard/agent-leads.jpg')}})"></div>
                                <div class="content">
                                    <div class="icon" style="background-image:url({{asset('images/icon-agentleads.svg')}})"></div>
                                    <h2 class="title">AGENT LEADS</h2>
                                </div>
                            </a>
                        </div>

                        <div class="item col-xs-12 col-sm-4">
                            <a href="#tab-deals" class="item-wrapper" data-toggle="tab">
                                <div class="bg" style="background-image:url({{asset('images/admin/dashboard/deals-made.jpg')}})"></div>
                                <div class="content">
                                    <div class="icon" style="background-image:url({{asset('images/icon-dealsmade.svg')}})"></div>
                                    <h2 class="title">DEALS MADE</h2>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>

               <div class="tab-content">
                   <div id="tab-customers" class="tab-pane active">
                       <div class="details-wrapper">
                            <div class="table-responsive default-table theme-blue">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th class="text-center">Customer ID</th>
                                            <th class="text-center">Name</th>
                                            <th class="text-center">Email</th>
                                            <th class="text-center">Phone #</th>
                                            <th class="text-center">Buyer?</th>
                                            <th class="text-center">Seller?</th>
                                            <th class="text-center">View Full Profile</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @forelse( $customers as $customer )
                                            <tr>
                                                <td class="text-center">{{ $customer->id }}</td>
                                                <td class="text-center">{{ $customer->asUser->name }}</td>
                                                <td class="text-center">{{ $customer->asUser->email }}</td>
                                                <td class="text-center">{{ $customer->asUser->phone_format }}</td>
                                                <td class="text-center">{{ $customer->buyerList()->count() > 0 ? 'Y' : 'N' }}</td>
                                                <td class="text-center">{{ $customer->sellerList()->count() > 0 ? 'Y' : 'N' }}</td>
                                                <td class="text-center"><a href="{{ route('admin.customers.profile', $customer) }}" class="blue">View Profile</a></td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="7">Customers not found..</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                       </div>
                   </div>

                   <div id="tab-agents" class="tab-pane fade">
                       <div class="details-wrapper">
                            <div class="table-responsive default-table theme-blue">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th class="text-center">Name</th>
                                            <th class="text-center">Email</th>
                                            <th class="text-center">Agency</th>
                                            <th class="text-center">Phone #</th>
                                            <th class="text-center">View Full Profile</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @forelse( $agents as $agent )
                                            <tr>
                                                <td class="text-center">{{ $agent->asUser->name }}</td>
                                                <td class="text-center">{{ $agent->asUser->email }}</td>
                                                <td class="text-center">{{ $agent->zillowApi()['proInfo']['businessName'] }}</td>
                                                <td class="text-center">{{ $agent->asUser->phone_format }}</td>
                                                <td class="text-center"><a href="{{ route('admin.agents.profile', $agent) }}" class="blue">View Profile</a></td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="5">Agents not found..</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                       </div>
                   </div>

                   <div id="tab-deals" class="tab-pane fade">
                       <div class="details-wrapper">
                            <div class="table-responsive default-table theme-blue">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th class="text-center">Transaction ID</th>
                                            <th class="text-center">Date Scheduled</th>
                                            <th class="text-center">Client's Name</th>
                                            <th class="text-center">Rebate</th>
                                            <th class="text-center">Deal Closed</th>
                                            <th class="text-center">View Details</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @forelse( $deals as $deal )
                                            <tr>
                                                <td class="text-center">{{ $deal->id }}</td>
                                                <td class="text-center">@dateFormat( $deal->until )</td>
                                                <td class="text-center">{{ $deal->customer->asUser->name }}</td>
                                                <td class="text-center">{{ $deal->selectedProposal() ? $deal->selectedProposal()->rebate_format : '
                                                ' }}</td>
                                                <td class="text-center">{{ $deal->closed_deal ? 'Y' : 'N' }}</td>
                                                <td class="text-center"><a href="{{ route('admin.deals.details', $deal)}}" class="blue">View Details</a></td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="6">Agents not found..</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                       </div>
                   </div>
               </div>

            </div>
        </div>
    </div>
</section>
@stop


<!-- Added Scripts -->
@section('scripts')

@stop