routes/admin.php
<?php

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function() {

	/*
	* Dashboard
	**/
	Route::get('/', 'DashboardController@index')->name('dashboard');

	/*
	* Deals
	**/
	Route::group(['prefix' => 'deals'], function() {
		Route::get('/', 'DealsController@index')->name('deals');
		Route::get('{list}/details', 'DealsController@details')->name('deals.details');
	});

	/*
	* Agents
	**/
	Route::group(['prefix' => 'agents'], function() {
		Route::get('/', 'AgentsController@index')->name('agents');
		Route::get('review', 'AgentsController@reviewAgents')->name('agents.review');
		Route::get('view', 'AgentsController@viewAgents')->name('agents.view');
		Route::get('deals', 'AgentsController@deals')->name('agents.deals');
		Route::post('search-results', 'AgentsController@searchResults')->name('agents.search-results');
		Route::get('{agent}/profile/{status?}', 'AgentsController@profile')->name('agents.profile');
		Route::post('{agent}/profile/store', 'AgentsController@storeProfile')->name('agents.profile.store');
		Route::post('{agent}/profile/store-qa', 'AgentsController@storeQA')->name('agents.profile.storeQA');
		Route::post('{agent}/profile/store-social', 'AgentsController@storeSocial')->name('agents.profile.storeSocial');
		Route::get('{agent}/profile/list/{list}/details', 'AgentsController@listDetails')->name('agents.profle.list-details');
		
		// ajax functions 
		Route::post('{agent}/approve', 'AgentsController@approve');
		Route::post('{agent}/reject', 'AgentsController@reject');
	});

	/*
	* Customer
	**/
	Route::group(['prefix' => 'customers'], function() {
		Route::get('/', 'CustomersController@index')->name('customers');
		Route::get('screen', 'CustomersController@customersToScreen')->name('customers.to-screen');
		Route::get('all', 'CustomersController@allCustomers')->name('customers.all');
		Route::get('without-agent', 'CustomersController@customersWithoutAgent')->name('customers.without-agent');
		Route::post('search-results', 'CustomersController@searchResults')->name('customers.search-results');
		Route::get('{customer}/profile/{status?}', 'CustomersController@profile')->name('customers.profile');
		Route::post('{customer}/profile/store', 'CustomersController@storeProfile')->name('customers.save-profile');
		Route::get('{customer}/profile/list/{list}/details', 'CustomersController@listDetails')->name('customers.profile.list-details');

		// Ajax
        Route::get('list/create-list', 'CustomersController@creatingList');
        Route::post('list/update-list', 'CustomersController@updateList');
        Route::get('list/{list}/edit-list', 'CustomersController@getList');
		Route::post('list/{list}/edit-agents', 'CustomersController@editAgents');
		Route::post('list/{list}/store-agents', 'CustomersController@storeAgents');
		Route::post('list/{list}/store-list-agents', 'CustomersController@storeListAgents');
		Route::post('{customer}/approve', 'CustomersController@approve');
		Route::post('{customer}/reject', 'CustomersController@reject');

	});

	/*
	* Process
	**/
	Route::group(['prefix' => 'process'], function() {
		Route::get('/', 'ProcessController@index')->name('process');
		Route::get('deals', 'ProcessController@deals')->name('process.deals');
	});

	/*
	* Settings
	**/
	Route::group(['prefix' => 'settings'], function(){
		Route::get('/', 'SettingsController@index')->name('settings');
		Route::get('create', 'SettingsController@create')->name('settings.create');
		Route::post('store', 'SettingsController@store')->name('settings.store');
		Route::get('{user}/edit', 'SettingsController@edit')->name('settings.edit');
		Route::post('{user}/update', 'SettingsController@update')->name('settings.update');
		Route::get('{user}/destroy', 'SettingsController@destroy')->name('settings.destroy');
	});

});

routes/user.php
<?php

Route::group(['namespace' => 'User'], function(){

	/*
	* Agent Routes
	**/
	require base_path('routes/agent.php');

	/*
	* Customer Routes
	**/
	require base_path('routes/customer.php');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Model\Agent;

Route::get('testmail', function() {
	$agent = \App\Model\Agent::findOrFail(28);
	Mail::to('jessie.sytian@gmail.com')->send(new \App\Mail\AgentSignupMail($agent));
});

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

Route::get('/login', 'HomeController@userLogin')->name('login');

Route::get('admin/login', 'HomeController@adminLogin')->name('admin.login');
	
/*
* Facebook Login
**/
Route::group(['prefix' => 'facebook'], function() {
	Route::get('login', 'Auth\LoginController@redirectToProvider')->name('facebook.login');
	Route::get('authenticated', 'Auth\LoginController@fbAuth')->name('facebook.authenticated');
});

/*
*  Public View Routes
**/
Route::get('/', 'HomeController@home')->name('home');

/*
* Buyers
**/
Route::group(['prefix' => 'buyers'], function() {
	Route::get('/', 'BuyersController@index')->name('buyers');
	Route::get('find-an-agent', 'BuyersController@findAgent')->name('buyers.find-agent');
	Route::get('guide', 'BuyersController@guide')->name('buyers.guide');
	Route::get('process', 'BuyersController@process')->name('buyers.process');
});

/*
* Sellers
**/
Route::group(['prefix' => 'sellers'], function() {
	Route::get('/', 'SellersController@index')->name('sellers');
	Route::get('find-an-agent', 'SellersController@findAgent')->name('sellers.find-agent');
	Route::get('guide', 'SellersController@guide')->name('sellers.guide');
	Route::get('process', 'SellersController@process')->name('sellers.process');
});

/*
* Agent
**/
Route::group(['prefix' => 'agent'], function() {
	Route::get('/', 'AgentsController@index')->name('agent');
	Route::get('register', 'AgentsController@register')->name('agent.register');	
	Route::post('validate-form', 'AgentsController@validateForm');
	Route::post('submit-registration', 'AgentsController@submitRegistration')->name('agent.submit-registration');
	Route::get('register-success', 'AgentsController@success');

	// fb registration
	Route::get('{user}/fb-register', 'AgentsController@fbRegister')->name('agent.fb-register');
});

Route::get('about-us', 'HomeController@about')->name('about');
Route::get('terms-and-condition', 'HomeController@terms')->name('terms');
Route::get('privacy-policy', 'HomeController@privacy')->name('privacy');
Route::get('resources', 'HomeController@resources')->name('resources');
Route::get('contact-us', 'HomeController@contact')->name('contact');
Route::get('find-an-agent', 'HomeController@findAgent')->name('find-agent');

// request a call / contact us
Route::post('request-call', 'HomeController@requestCall')->name('request-call');
Route::post('contact-us', 'HomeController@contactUs')->name('request-contact');

/*
* Registration
**/
Route::group(['prefix' => 'register'], function() {
	Route::get('/', 'HomeController@register')->name('register');
    Route::post('/', 'HomeController@getForms')->name('get.forms');
	Route::post('validate-form', 'HomeController@validateForm');
	Route::post('store', 'HomeController@storeRegistration');
	Route::get('success/{user?}', 'HomeController@success')->name('register.success');

	// fb registration
	Route::get('{user}/fb-register', 'HomeController@fbRegister')->name('register.fb-register');
});

Route::group(['middleware' => 'auth'], function() {

	/*
	* Admin Routes
	**/
	require base_path('routes/admin.php');	

	/*
	* Regular User Routes
	**/
	require base_path('routes/user.php');
});

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Support\Facades\File;
use ImageResize;
use App\Model\Role;
use App\Model\Agent;
use App\Model\Customer;
use App\Model\Activity;
use Watson\Validating\ValidatingTrait;
use Illuminate\Support\Facades\Storage;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    use ValidatingTrait;

    protected $throwValidationExceptions = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'username',
        'email',
        'phone_num'
    ];

    protected $rules = [
        'first_name' => 'required',
        'last_name' => 'required',
        'email' => 'required|unique|email',
        'password' => 'required|min:8',
        //'phone_num' => 'required|numeric|min:11|nullable',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    /*
    * Relations
    **/
    public function role() 
    {
        return $this->belongsTo(Role::class);
    }

    public function asCustomer() 
    {
        return $this->hasOne(Customer::class);
    }

    public function asAgent() 
    {
        return $this->hasOne(Agent::class);
    }

    public function activities() 
    {
        return $this->hasMany(Activity::class);
    }

    /*
    *  Helper Methods
    **/
    public function isAdmin() 
    {

        if( $this->role ) 
        {
            if($this->role->slug != 'administrator') 
            {
                return false;
            }
        } else {
            return false;
        }

        return true;

    }

    public function isCustomer() 
    {
        if( !$this->asCustomer ) {
            return false;
        }
        return true;
    }    

    public function isAgent() 
    {   
        if( !$this->asAgent ) {
            return false;
        }
        return true;
    }   

    public function isRegularUser() 
    {

        if( $this->role ) {
            if( $this->role->slug != 'user' )
            {
                return false;
            }
        } else {
            return false;
        }

        return true;

    }

    public function isNewUser()
    {
        return $this->created_at->isSameDay(Carbon::today()) ?: false;
    }

    /*
    * Getter Methods
    **/
    public function getNameAttribute() 
    {
        return $this->first_name . " " . $this->last_name;
    }

    public function getphoneFormatAttribute() 
    {

        $phone = preg_replace(array('/\+/', '/\(/', '/\)/', '/\s/', '/\./', '/\-/', '/[a-zA-Z]/'), array(''), $this->phone_num);
        $phone = str_split($phone, 1);
        $phone = array_chunk($phone, 3);

        $phone[0] = '(' . implode('', $phone[0]) . ') ';

        if( isset( $phone[1] ) ) {
            $phone[1] = implode('', $phone[1]) . (count($phone) > 2 ? '-' : '');
        }

        if( count( $phone ) > 2 ) {
            for( $i = 2; $i < count($phone); $i++ ) {
                $phone[$i] = implode('', $phone[$i]);
            }
        }

        $phone = implode('', $phone);

        return $phone;

    }

    public function getProfilePhotoAttribute()
    {
        $publicPath = '';
        $profilePhoto = asset(Storage::disk('world')->url('profile-photos/' . $this->photo));
        $publicPath = public_path('storage/profile-photos/' . ($this->photo ?: 'false'));

        if( $this->photo && File::exists($publicPath))
        {
            $resizedPhoto = ImageResize::make($profilePhoto)->fit(278, 278)->encode('data-url');
        } else {
            $resizedPhoto = null;
        }

        return File::exists($publicPath) ? $resizedPhoto->encoded : null;
    }

}

app/Http/Controllers/Admin/AgentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\Model\Agent;
use App\Model\Listing;
use App\Model\Activity;
use App\Model\Proposal;
use Illuminate\Http\Request;
use App\Mail\VerifiedAgent;
use Illuminate\Support\Facades\Mail;
use App\Http\Controllers\Controller;

class AgentsController extends Controller
{
    
	public function index() {
		return view('admin.agent.index');
	}

	public function reviewAgents() 
	{
		$agents = new Agent;

		$agents = $agents->search(['asUser'], 10, ['approved' => 0, 'rejected' => 0]);

		return view('admin.agent.review', compact('agents'));
	}

	public function viewAgents() 
	{

		$agents = new Agent;		

		$agents = $agents->search(['asUser'], 10);

		return view('admin.agent.view', compact('agents'));
	}

	public function deals() 
	{
		return view('admin.agent.deals');
	}

	public function searchResults(Request $request) 
	{

		$with = [
			'asUser'
		];

		$agents = new Agent;

		$agents = $agents->search($with, 10, [], $request);

		return view('admin.agent.search-results', compact('agents'));
	}

	public function profile(Agent $agent, $status = null, Request $request) 
	{

		$lists = Listing::whereHas('proposals', function($proposal) use($agent) {
			$proposal->where('agent_id', $agent->id);
		})->get();

		$zillowApi = $agent->zillowApi();

		$buyersList = $agent->outstandingDeals()
							->with('customer.asUser')
							->where('list_type', 'buyer')
							->get()
							->sortByDesc('until');

		$sellersList = $agent->outstandingDeals()
							 ->with(['customer.asUser'])
							 ->where('list_type', 'seller')
							 ->get()
							 ->sortByDesc('until');

		// activities
		$activities = $agent->asUser->activities;
		$activities = $activities->sortByDesc('created_at');

		// proposals
		$proposals = $agent->proposals->each(function($proposal) {
			$proposal->load('listing.customer.asUser');
		})->sortByDesc('created_at');

		// requests
		$requests = $agent->deals->each(function($deal){
			$deal->load('customer.asUser');
		});

		$pitches = $proposals->merge( $requests )->sortByDesc('created_at');

		if( $status && $status == 'approved' )
		{
			session(['success' => 'This agent has been approved!']);
		} elseif( $status && $status == 'rejected' ) {
			session(['success' => 'This agent has been rejected!']);
		} else {
			// remove all session
			//$request->session()->forget('success');
		}

		return view('admin.agent.profile', compact('agent', 'zillowApi', 'buyersList', 'sellersList', 'activities', 'pitches'));
	}

	public function storeProfile(Agent $agent, Request $request)
	{

		$agent->setOtherData([
			'admin_name' => $request->admin_name,
			'admin_email' => $request->admin_email,
			'admin_phone' => $request->admin_phone,
			'admin_as_broker' => $request->admin_as_broker,
			'admin_as_agent' => $request->admin_as_agent,
			'admin_broker' => $request->admin_broker,
			'admin_agency' => $request->admin_agency,
			'admin_other' => $request->admin_other,
			'admin_license' => $request->admin_license
		]);

		return redirect()->back()->withSuccess('Profile successfuly saved.');

	}

	public function storeQA(Agent $agent, Request $request)
	{

		$agent->setOtherData([
			'question_1' => $request->question_1,
			'question_2' => $request->question_2
		]);

		return redirect()->back()->withSuccess('Q+A successfuly saved.');

	}

	public function storeSocial(Agent $agent, Request $request)
	{

		$agent->setOtherData([
			'admin_linkedin_url' => $request->admin_linkedin_url,
			'admin_website_url' => $request->admin_website_url,
			'admin_zillow_url' => $request->admin_zillow_url
		]);

		return redirect()->back()->withSuccess('Social URLs successfuly saved.');

	}

	public function listDetails(Agent $agent, Listing $list) 
	{

		$list->load('customer.asUser');

		return view('admin.agent.list-details', compact('list'));
	}

	public function approve(Agent $agent) 
	{
		$agent->approved = 1;
		$agent->rejected = 0;

		if( $agent->save() ) {
			$message = 'success';

			// add activities
			$activity = new Activity;
			$action = 'Profile was approved.';
			$activity->addActivity($agent->asUser->id, $action);

			Mail::to($agent->asUser->email)->send(new VerifiedAgent($agent));

		} 
		else {
			$message = 'error';
		}

		return response()->json(compact('message'));

	}

	public function reject(Agent $agent) 
	{
		$agent->approved = 0;
		$agent->rejected = 1;

		if( $agent->save() ) {
			$message = 'success';

			// add activities
			$activity = new Activity;
			$action = 'Profile was rejected.';
			$activity->addActivity($agent->asUser->id, $action);

		} 
		else {
			$message = 'error';
		}

		return response()->json(compact('message'));

	}

}

resources/views/user/agent/customer-list.blade.php
@extends('layouts.default')

@section('styles')
	<style type="text/css">
		
	</style>
@stop

@section('body-class')
	customer-profile pagetitle-off
@stop

@section('content')
<section id="customer-profile" class="default-section">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-md-4">
				<div class="photo"><img class="img-responsive" src="{{ $customer->asUser->profile_photo ? $customer->asUser->profile_photo : asset('images/user-blank.svg') }}"></div>
			</div>
			<div class="col-xs-12 col-md-8">
				<div class="info">
					<h1 class="name">{{ $customer->asUser->name }}</h1>
					{{--<div class="location"><i class="fa fa-map-marker" aria-hidden="true"></i> Highlands Ranch, CO</div>--}}
					@if( $customer->asUser->city )
						<div class="location"><i class="fa fa-map-marker" aria-hidden="true"></i> {{ $customer->asUser->city . " " . $customer->asUser->state }}</div>
					@endif
					<div class="moreinfo">
						<div class="listitem">
							<div class="title">Email</div><div class="content"><a href="mailto:{{ $customer->asUser->email }}">{{ $customer->asUser->email }}</a></div>
						</div>
						<div class="listitem">
							<div class="title">City</div><div class="content">{{ $customer->asUser->city ?: '--' }}</div>
						</div>
						<div class="listitem">
							<div class="title">State</div><div class="content">{{ $customer->asUser->state ?: '--' }}</div>
						</div>
						<div class="listitem">
							<div class="title">Phone</div><div class="content"><a href="tel:@phoneNum($authUser->phone_num)">{{ $customer->asUser->phone_format }}</a></div>
						</div>
					</div>
					<div class="ctrls">
						@php $deal = $list; @endphp
						<a href="{{ route('agent.list.details', $deal) }}" class="btn btn-pink btn-round hvr-rectangle-out">Edit Proposal</a>
						<a href="{{ route('agent.customer.profile', $customer) }}" class="btn btn-blue btn-round hvr-rectangle-out">See Customer's View</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section id="customer-moreinfo" class="default-section">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-md-8 col-md-push-4">

				<div class="cp-container">
					<h2 class="heading">About My Home Needs</h2>
					<div class="content">
						@if($list->list_type == 'buyer')
							<p>Hi, my name is {{ $customer->asUser->name }}.  I am looking to buy a {{ $list->property->human_display }} in the {{ $list->complete_address }} area {{ $list->text_until ? $list->text_until : $list->until }}.</p>
							<p>My budget is approximately {{ $list->text_budget ? $list->text_budget : $list->budget }}. and {{ $customer->lender_status }} for a mortgage.
								@if($list->bedrooms && $list->bathrooms)<br><br>I am looking for a home that is {{ $list->bedrooms }} bedrooms and {{ $list->bathrooms }} bathrooms.@endif
							</p>
						@else
							<p>Hi, my name is {{ $customer->asUser->name }}. I am looking to sell my {{ number_format($list->sq_feet_max, 0) }} square foot {{ $list->property->human_display }} that is {{ $list->bedrooms }} bedrooms and {{ $list->bathrooms }} in the {{ $list->complete_address }} area. {{ $list->text_until ? $list->text_until : $list->until }}.
								<br><br>I believe my home is worth between {{ $list->text_budget ? $list->text_budget : $list->budget }}.
								<br><br>I look forward to hearing from you.
							</p>
						@endif
						{{--<p>Hi, my name is Scott Sterling.  I am looking to buy a townhouse in the Highlands Ranch, CO area in the next month.</p>
						<p>My budget is approximately $400,000 and I have not been pre-approved and I have not been pre-qualified for a mortgage. I am looking for a home that is 3 bedrooms and 2 bathrooms.</p>--}}
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-md-4 col-md-pull-8">
				<div class="sidebar cp-container">
					<div class="listitem">
						<div class="title">Date Signed Up</div>
						<div class="content">@dateFormat($list->created_at)</div>
					</div>
					<div class="listitem">
						<div class="title">Proposal Submitted</div>
						@php
							$latestProposal = $list->proposals->sortByDesc('created_at')->first();
						@endphp
						@if ($latestProposal)
							<div class="content">{{ $latestProposal->created_at->format('F d, Y') }}</div>
						@endif
					</div>
					<div class="listitem">
						<div class="title">Have They Selected An Agent</div>
						<div class="content">{{ $list->selectedAgent ? 'Yes' : 'Not Yet' }}</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
@stop

@section('scripts')
@stop

resources/views/user/agent/customer-profile.blade.php
@extends('layouts.default')

@section('styles')
	<style type="text/css">
		.panel-group a {
			display: block;			
			padding: 20px 15px;
		}

		.panel-group a:hover, 
		.panel-group a:focus {
			text-decoration: none;
		}

		.panel-group .panel-heading {
			padding: 0;
		}
	</style>
@stop

@section('body-class')
	customer-profile pagetitle-off
@stop

@section('content')
<section id="customer-profile" class="default-section">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-md-4">
				<div class="photo"><img class="img-responsive" src="{{ $customer->asUser->profile_photo ? $customer->asUser->profile_photo : asset('images/user-blank.svg') }}"></div>
			</div>
			<div class="col-xs-12 col-md-8">
				<div class="info">
					<h1 class="name">{{ $customer->asUser->name }}</h1>
					@if( $customer->asUser->city )
						<div class="location"><i class="fa fa-map-marker" aria-hidden="true"></i> {{ $customer->asUser->city . " " . $customer->asUser->state }}</div>
					@endif
					<div class="moreinfo">
						<div class="listitem">
							<div class="title">Email</div><div class="content"><a href="mailto:{{ $customer->asUser->email }}">{{ $customer->asUser->email }}</a></div>
						</div>
						<div class="listitem">
							<div class="title">City</div><div class="content">{{ $customer->asUser->city ?: '--' }}</div>
						</div>
						<div class="listitem">
							<div class="title">State</div><div class="content">{{ $customer->asUser->state ?: '--' }}</div>
						</div>
						<div class="listitem">
							<div class="title">Phone</div><div class="content"><a href="tel:@phoneNum($authUser->phone_num)">{{ $customer->asUser->phone_format }}</a></div>
						</div>
					</div>
					<div class="ctrls">
						<a href="" class="btn btn-pink btn-round hvr-rectangle-out">Message</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section id="customer-moreinfo" class="default-section">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-md-8 col-md-push-4">

				@if( $listings->count() > 0 )

					<div class="panel-group" id="accordion">
						@foreach( $listings as $list )
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ $list->id }}">{{ $list->property->human_display }}</a>
									</h4>
								</div>
								<div id="collapse{{ $list->id }}" class="panel-collapse collapse {{ $loop->first ? 'in' : '' }}">
									<div class="panel-body profile cp-container">
										<div class="listitem">
											<div class="title">Are you looking to buy a home or sell a home?</div>
											<div class="content">{{ $list->list_type == 'buyer' ? 'Sell Home' : 'Buy Home' }}</div>
										</div>
										<div class="listitem">
											<div class="title">Where are you looking to buy / sell?</div>
											<div class="content">{{ $list->complete_address }}</div>
										</div>
										<div class="listitem">
											<div class="title">Home much are you hoping to spend/sell on a home?</div>
											<div class="content">
												@if( $list->budget )
													{{ $list->budget }}
												@else
													{{ 'N/A' }}
												@endif
											</div>
										</div>
										<div class="listitem">
											<div class="title">What kind of property are you buying/selling?</div>
											<div class="content">{{ $list->property->human_display }}</div>
										</div>
										<div class="listitem">
											<div class="title">How soon are you looking to buy/sell?</div>
											<div class="content">
												@if($list->text_until)
													{{ $list->text_until }}
												@else
													@dateFormat( $list->until )
												@endif
											</div>
										</div>
										<div class="listitem">
											<div class="title">Are you pre-approved by a lender?</div>
											<div class="content">{{ $customer->lender_status }}</div>
										</div>
									</div>
								</div>
							</div>
						@endforeach
					</div>

				@else

					<div class="profile cp-container">
						Listings not found..
					</div>

				@endif

			</div>
			<div class="col-xs-12 col-md-4 col-md-pull-8">
				<div class="sidebar cp-container">
					<div class="listitem">
						<div class="title">Date Signed Up</div>
						<div class="content">@dateFormat($authUser->created_at)</div>
					</div>
					{{--<div class="listitem">
						<div class="title">Have They Selected An Agent</div>
						<div class="content">Yes</div>
					</div>
					<div class="listitem">
						<div class="title">Proposal Submitted</div>
						<div class="content">September 10, 2017</div>
					</div>--}}
				</div>
			</div>
		</div>
	</div>
</section>
@stop

@section('scripts')
@stop