routes/admin.php
<?php

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function() {

	/*
	* Dashboard
	**/
	Route::get('/', 'DashboardController@index')->name('dashboard');

	/*
	* Deals
	**/
	Route::group(['prefix' => 'deals'], function() {
		Route::get('/', 'DealsController@index')->name('deals');
		Route::get('{list}/details', 'DealsController@details')->name('deals.details');
	});

	/*
	* Agents
	**/
	Route::group(['prefix' => 'agents'], function() {
		Route::get('/', 'AgentsController@index')->name('agents');
		Route::get('review', 'AgentsController@reviewAgents')->name('agents.review');
		Route::get('view', 'AgentsController@viewAgents')->name('agents.view');
		Route::get('deals', 'AgentsController@deals')->name('agents.deals');
		Route::post('search-results', 'AgentsController@searchResults')->name('agents.search-results');
		Route::get('{agent}/profile/{status?}', 'AgentsController@profile')->name('agents.profile');
		Route::post('{agent}/profile/store', 'AgentsController@storeProfile')->name('agents.profile.store');
		Route::post('{agent}/profile/store-qa', 'AgentsController@storeQA')->name('agents.profile.storeQA');
		Route::post('{agent}/profile/store-social', 'AgentsController@storeSocial')->name('agents.profile.storeSocial');
		Route::get('{agent}/profile/list/{list}/details', 'AgentsController@listDetails')->name('agents.profle.list-details');
		
		// ajax functions 
		Route::post('{agent}/approve', 'AgentsController@approve');
		Route::post('{agent}/reject', 'AgentsController@reject');
	});

	/*
	* Customer
	**/
	Route::group(['prefix' => 'customers'], function() {
		Route::get('/', 'CustomersController@index')->name('customers');
		Route::get('screen', 'CustomersController@customersToScreen')->name('customers.to-screen');
		Route::get('all', 'CustomersController@allCustomers')->name('customers.all');
		Route::get('without-agent', 'CustomersController@customersWithoutAgent')->name('customers.without-agent');
		Route::post('search-results', 'CustomersController@searchResults')->name('customers.search-results');
		Route::get('{customer}/profile/{status?}', 'CustomersController@profile')->name('customers.profile');
		Route::post('{customer}/profile/store', 'CustomersController@storeProfile')->name('customers.save-profile');
		Route::get('{customer}/profile/list/{list}/details', 'CustomersController@listDetails')->name('customers.profile.list-details');

		// Ajax
        Route::get('list/create-list', 'CustomersController@creatingList');
        Route::post('list/update-list', 'CustomersController@updateList');
        Route::get('list/{list}/edit-list', 'CustomersController@getList');
		Route::post('list/{list}/edit-agents', 'CustomersController@editAgents');
		Route::post('list/{list}/store-agents', 'CustomersController@storeAgents');
		Route::post('list/{list}/store-list-agents', 'CustomersController@storeListAgents');
		Route::post('{customer}/approve', 'CustomersController@approve');
		Route::post('{customer}/reject', 'CustomersController@reject');

	});

	/*
	* Process
	**/
	Route::group(['prefix' => 'process'], function() {
		Route::get('/', 'ProcessController@index')->name('process');
		Route::get('deals', 'ProcessController@deals')->name('process.deals');
	});

	/*
	* Settings
	**/
	Route::group(['prefix' => 'settings'], function(){
		Route::get('/', 'SettingsController@index')->name('settings');
		Route::get('create', 'SettingsController@create')->name('settings.create');
		Route::post('store', 'SettingsController@store')->name('settings.store');
		Route::get('{user}/edit', 'SettingsController@edit')->name('settings.edit');
		Route::post('{user}/update', 'SettingsController@update')->name('settings.update');
		Route::get('{user}/destroy', 'SettingsController@destroy')->name('settings.destroy');
	});

});

routes/user.php
<?php

Route::group(['namespace' => 'User'], function(){

	/*
	* Agent Routes
	**/
	require base_path('routes/agent.php');

	/*
	* Customer Routes
	**/
	require base_path('routes/customer.php');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Model\Agent;

Route::get('testmail', function() {
	$agent = \App\Model\Agent::findOrFail(28);
	Mail::to('jessie.sytian@gmail.com')->send(new \App\Mail\AgentSignupMail($agent));
});

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

Route::get('/login', 'HomeController@userLogin')->name('login');

Route::get('admin/login', 'HomeController@adminLogin')->name('admin.login');
	
/*
* Facebook Login
**/
Route::group(['prefix' => 'facebook'], function() {
	Route::get('login', 'Auth\LoginController@redirectToProvider')->name('facebook.login');
	Route::get('authenticated', 'Auth\LoginController@fbAuth')->name('facebook.authenticated');
});

/*
*  Public View Routes
**/
Route::get('/', 'HomeController@home')->name('home');

/*
* Buyers
**/
Route::group(['prefix' => 'buyers'], function() {
	Route::get('/', 'BuyersController@index')->name('buyers');
	Route::get('find-an-agent', 'BuyersController@findAgent')->name('buyers.find-agent');
	Route::get('guide', 'BuyersController@guide')->name('buyers.guide');
	Route::get('process', 'BuyersController@process')->name('buyers.process');
});

/*
* Sellers
**/
Route::group(['prefix' => 'sellers'], function() {
	Route::get('/', 'SellersController@index')->name('sellers');
	Route::get('find-an-agent', 'SellersController@findAgent')->name('sellers.find-agent');
	Route::get('guide', 'SellersController@guide')->name('sellers.guide');
	Route::get('process', 'SellersController@process')->name('sellers.process');
});

/*
* Agent
**/
Route::group(['prefix' => 'agent'], function() {
	Route::get('/', 'AgentsController@index')->name('agent');
	Route::get('register', 'AgentsController@register')->name('agent.register');	
	Route::post('validate-form', 'AgentsController@validateForm');
	Route::post('submit-registration', 'AgentsController@submitRegistration')->name('agent.submit-registration');
	Route::get('register-success', 'AgentsController@success');

	// fb registration
	Route::get('{user}/fb-register', 'AgentsController@fbRegister')->name('agent.fb-register');
});

Route::get('about-us', 'HomeController@about')->name('about');
Route::get('terms-and-condition', 'HomeController@terms')->name('terms');
Route::get('privacy-policy', 'HomeController@privacy')->name('privacy');
Route::get('resources', 'HomeController@resources')->name('resources');
Route::get('contact-us', 'HomeController@contact')->name('contact');
Route::get('find-an-agent', 'HomeController@findAgent')->name('find-agent');

// request a call / contact us
Route::post('request-call', 'HomeController@requestCall')->name('request-call');
Route::post('contact-us', 'HomeController@contactUs')->name('request-contact');

/*
* Registration
**/
Route::group(['prefix' => 'register'], function() {
	Route::get('/', 'HomeController@register')->name('register');
    Route::post('/', 'HomeController@getForms')->name('get.forms');
	Route::post('validate-form', 'HomeController@validateForm');
	Route::post('store', 'HomeController@storeRegistration');
	Route::get('success/{user?}', 'HomeController@success')->name('register.success');

	// fb registration
	Route::get('{user}/fb-register', 'HomeController@fbRegister')->name('register.fb-register');
});

Route::group(['middleware' => 'auth'], function() {

	/*
	* Admin Routes
	**/
	require base_path('routes/admin.php');	

	/*
	* Regular User Routes
	**/
	require base_path('routes/user.php');
});

app/Http/Controllers/Admin/SettingsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\Model\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class SettingsController extends Controller
{
    
	public function index() 
	{
		$users = User::where(function($user) {
			$user->whereHas('role');
		})->get();
		return view('admin.setting.index', compact('users'));
	}

	public function create() 
	{
		$roles = Role::pluck('name', 'id')->toArray();

		return  view('admin.setting.create', compact('roles'));
	}

	public function store(Request $request) 
	{	

		try {

			$user = new User;
			$user->fill($request->all());

			$user->password = bcrypt($request->password);
			$user->role_id = $request->role_id;

			$user->saveOrFail();

			return redirect()->route('admin.settings')->withSuccess('User successfuly added.');

		} catch( \Watson\Validating\ValidationException $e ) {
			
			$errors = $e->getErrors();
			return redirect()->back()
							 ->withErrors($errors)
							 ->withInput();
		}				

	}

	public function edit(User $user)
	{
		$roles = Role::get()->pluck('name', 'id');
		return view('admin.setting.edit', compact('roles', 'user'));
	}

	public function update(Request $request, User $user)
	{

		try {

			$user->fill($request->all());
			$user->saveOrFail();

			return redirect()->route('admin.settings')->withSuccess('User successfuly updated.'); 

		} catch( \Watson\Validating\ValidationException $e ) {

			$errors = $e->getErrors();
			return redirect()->back()
							 ->withErrors($errors)
							 ->withInput();

		}

	}

	public function destroy(User $user) {
		$user->delete();
		return redirect()->route('admin.settings')->withSuccess('User successfuly deleted.');
	}

}

resources/views/admin/setting/create.blade.php
@extends('layouts.default')


@section('body-class')
	settings dashboard
@stop

@section('page-title')
	Create New User
@stop

@section('content')
<section class="settings-dashboard">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
					
					@include('admin.setting.form', [
						'route' => 'admin.settings.store',
						'user' => new App\User
					])


			</div>
		</div>
	</div>
</section>
@stop

resources/views/admin/setting/edit.blade.php
@extends('layouts.default')


@section('body-class')
	settings dashboard
@stop

@section('page-title')
	Update User
@stop

@section('content')
<section class="settings-dashboard">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
					
					@include('admin.setting.form', [
						'route' => ['admin.settings.update', $user],
						'user' => $user
					])


			</div>
		</div>
	</div>
</section>
@stop

resources/views/admin/setting/form.blade.php
@include('partials.form-errors')

{!! Form::model($user, ['route' => $route, 'class' => 'default-form']) !!}
		
	<div class="row">
		<div class="col-xs-12 col-sm-6">							
			<div class="form-group">
				<label class="control-label" for="first_name">First Name<span class="important">*</span></label>
				{!! Form::text('first_name', null, ['class' => 'form-control', 'id' => 'first_name']) !!}
			</div>			
		</div>
		<div class="col-xs-12 col-sm-6">
			<div class="form-group">
				<label class="control-label" for="last_name">Last Name<span class="important">*</span></label>
				{!! Form::text('last_name', null, ['class' => 'form-control', 'id' => 'last_name']) !!}		
			</div>
		</div>
		<div class="col-xs-12 col-sm-6">
			<div class="form-group">
				<label class="control-label" for="email">Email<span class="important">*</span></label>
				{!! Form::email('email', null, ['class' => 'form-control', 'id' => 'email']) !!}
			</div>			
		</div>
		<div class="col-xs-12 col-sm-6">
			<div class="form-group">
				<label class="control-label" for="username">Username</label>
				{!! Form::text('username', null, ['class' => 'form-control', 'id' => 'username']) !!}
			</div>			
		</div>
		<div class="col-xs-12 col-sm-6">
			<div class="form-group">
				<label class="control-label" for="email">Password<span class="important">*</span></label>
				{!! Form::password('password', ['class' => 'form-control', 'id' => 'password']) !!}		
			</div>			
		</div>
		<div class="col-xs-12 col-sm-6">
			<div class="form-group">
				<label class="control-label" for="username">Confirm Password<span class="important">*</span></label>
				{!! Form::password('comfirm_password', ['class' => 'form-control', 'placeholder' => 'Re-type your Password']) !!}
			</div>			
		</div>
		<div class="col-xs-12">
			<div class="form-group">
				<label class="control-label" for="phone_num">Phone Number</label>
				{!! Form::text('phone_num', null, ['class' => 'form-control']) !!}
			</div>
		</div>
		<div class="col-xs-12">
			<div class="form-group">
				<label class="control-label" for="role_id">Account Type</label>
				{!! Form::select('role_id', $roles, null, ['class' => 'form-control', 'placeholder' => 'Please select User Role']) !!}
			</div>
		</div>

	
		<div class="col-xs-12">
			<div class="form-controls">
				<a class="btn btn-blue  " href="{{ route('admin.settings') }}">Cancel</a>
				<button class="btn btn-pink  ">Submit</button>
			</div>
		</div>
	</div>
{!! Form::close() !!}

resources/views/admin/setting/index.blade.php
@extends('layouts.default')

<!-- Added Styles -->
@section('styles')
@stop

@section('body-class')
	settings
@stop

@section('page-title')
	Settings
@stop
@section('page-controls')
<div class="controls">
	<a href="{{ route('admin.settings.create') }}" class="btn btn-pink  ">Add a new user</a>
</div>
@stop
<!-- Content -->
@section('content')

<section class="settings-dashboard">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="table-responsive default-table">
					<table class="table">
						<thead>
							<tr>
								<th>Name</th>
								<th>Email Address</th>
								<th>User-Type</th>
								<th class="text-center">Actions</th>
							</tr>
						</thead>
						<tbody>
							@forelse( $users as $user )
								<tr>
									<td>{{ $user->name }}</td>
									<td>{{ $user->email }}</td>
									<td>{{ $user->role->name  }}</td>
									<td class="text-center">
										<a class="table-ctrls" href="{{ route('admin.settings.edit', $user) }}" title="edit">
											<span class="fa fa-pencil-square-o text-info"></span>
										</a>
										<a class="table-ctrls" href="{{ route('admin.settings.destroy', $user) }}" class="confirm" title="delete">
											<span class="fa fa-trash fa-2 text-danger"></span>
										</a>
									</td>
								</tr>
							@empty
								<tr><td colspan="4">Users not found.</td></tr>
							@endforelse		
						</tbody>
					</table>	
				</div>


			</div>
		</div>
	</div>
</section>

@stop


<!-- Added Scripts -->
@section('scripts')

@stop